/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Greeting = IDL.Record({
  'message' : IDL.Text,
  'recipientName' : IDL.Text,
});

export const idlService = IDL.Service({
  'createGreeting' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getGreeting' : IDL.Func([IDL.Text], [Greeting], ['query']),
  'listAllGreetings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Greeting))],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Greeting = IDL.Record({
    'message' : IDL.Text,
    'recipientName' : IDL.Text,
  });
  
  return IDL.Service({
    'createGreeting' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getGreeting' : IDL.Func([IDL.Text], [Greeting], ['query']),
    'listAllGreetings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Greeting))],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };